### ISSUE TITLE
Appointment Management API adn DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#10]
# User Story
As a Doctor, I want to view and manage my appointments, so I can keep track of my schedule and update appointment details.

## Description
Develop APIs and DB query for appointment management, allowing doctors to view and update their appointment schedules.

## Tasks:
- [x] Implement API to fetch all appointments for a doctor.
- [x] Implement API to update appointment details.
- [x] Implement API to cancel appointments.
- [x] Write the corresponding unit test.
- [x] Implement DB query update and fetch all appointments for doctor and for patients
