### ISSUE TITLE
Password Reset API TBD

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#12]
# User Story
As a user, I want to reset my password if I forget it, so that I can regain access to my account.

## Description
Implement an API that allows users to reset their passwords by requesting a password reset link via email.

## Tasks:
- [ ] Create an API for requesting a password reset link.
- [ ] Implement email service to send the reset link to the user.
- [ ] API to validate the reset link and update the password.
- [ ] Secure the process (for preventing abuse and such).
