### ISSUE TITLE
Room Management API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#13]
## Description
Develop an API that allows the Admin to manage room assignments, mark rooms as occupied/available, and view room statuses.

## Tasks:
- [ ] Implement API to create and assign rooms.
- [ ] Implement API to update room availability.
- [ ] Create API to fetch available and occupied rooms.
- [ ] Implement Query to get all available and booked rooms.
- [ ] Write the corresponding unit test.
- [ ] Implement room assignment logic for patient admissions.
