### ISSUE TITLE
Payment Reporting API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#14]
## Description
Create an API that generates reports for payments made by patients. The Admin should be able to view overall payment data and filter payments by patient, doctor, or time period.

## Tasks:
- [ ] Implement API to generate payment reports.
- [ ] Write the corresponding unit test.
- [ ] Implement DB Query for payments.
