### ISSUE TITLE
Prescription Management API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#16]
## Description
Develop an API and DB that allows doctors to create, update, and manage prescriptions for their patients.

## Tasks:
- [ ] Implement API to create new prescriptions.
- [ ] Implement DB query for creation of new prescriptions.
- [ ] Implement API to view prescription history for a patient.
- [ ] Implement DB query to get all prescriptions.
- [ ] Secure the API to allow only authorized doctors access.
- [ ] Write the corresponding unit test.
