### ISSUE TITLE
View Medical Records API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#17]
# User Story
As a User/ Patient, I want to view my medical records so that I can keep track of my health and any treatments I’ve received.

## Description
Implement an API that allows patients to securely view their own medical records, including diagnoses, treatments, and prescriptions.

## Tasks:
- [ ] Implement API to get,create,delete and update a patient's medical records.
- [ ] Ensure data includes diagnoses, treatments and prescriptions.
- [ ] Create Query to get all medical records of patient.
- [ ] Secure the API so only the respective patient can view their data.
- [ ] Write the corresponding unit test.
