### ISSUE TITLE
Appointment Reminder Notifications

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#18]
## Description
Develop an API that sends automated reminders to patients about upcoming appointments via email or SMS.

## Tasks:
- [ ] Set up a scheduler to trigger reminders a day before the appointment.
- [ ] Allow patients to opt-in/opt-out of notifications via API and save that in DB.
- [ ] Write the corresponding test.
