### ISSUE TITLE
Login APIs

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#4]
## Description
Implement APIs for user registration and login, ensuring password encryption and secure JWT token handling.

## Tasks:
- [x] Create a registration API that stores user details in the database (only admin can add/register doctors or patients.
- [x] Create a login API that generates JWT upon successful login.
- [x] Encrypt user passwords.
- [x] Securely store and handle JWT tokens.
- [x] Write the corresponding unit test.
