### ISSUE TITLE
Patient Management API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#5]
# User Story
As an Admin, I want to manage patient records so that I can add, edit, and delete patients from the system.

## Description
Develop APIs for managing patients, including functionality to create, update, view, and delete patient records.

## Tasks:
- [ ] Implement API and DB query to create new patient records.
- [ ] Implement API and DB query to update existing patient records.
- [ ] Implement API and DB query to delete patient records.
- [ ] Implement API and DB query to fetch all patients.
- [ ] Write the corresponding unit test.
