### ISSUE TITLE
Admin Management API 

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#6]
## Description
Create APIs and DB queries for managing hospital staff, allowing the Admin to view, add, update, and delete staff members.

## Tasks:
- [ ] Implement API to create new staff members.
- [ ] Implement API to update existing staff details.
- [ ] Implement API to delete staff members.
- [ ] Implement API to fetch all staff.
- [ ] Implement DB query to get all staff members.
- [ ] Implement DB query to update staff member.
- [ ] Implement DB query to delete staff member.
- [ ] Write the corresponding unit test.
