### ISSUE TITLE
Appointment Booking API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#8]
# User Story
As a Patient, I want to book appointments online, so I can schedule visits with doctors easily.

## Description
Create an API for patients to book appointments and manage their appointment schedule.

## Tasks:
- [x] Implement API to book new appointments.
- [x] Write the corresponding unit test.
- [x] Implement API to view booked appointments.
- [x] Implement API to cancel appointments.
- [x] Implement DB query to update appointments.
- [x] Implement DB query to delete appointments.
- [x] Implement DB query to insert appointments.
