### ISSUE TITLE
Billing API and DB

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-backend#9]
## Description
Develop an API to allow patients to view billing details and make payments securely.

## Tasks:
- [ ] Implement DB query to fetch billing details for patients.
- [ ] Implement API to display payment history.
- [ ] Write the corresponding unit test.
